<a href="https://colab.research.google.com/github/pushpanjalisingh986-sketch/ML_Vectorization/blob/main/ML_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**VECTORIZATION** = we replace LOOPS by NumPY, matrix operations for faster Execution.

In modern Machine Learning, we perform vectorization across 4 core levels:

1. Basic Array Operations (Element-wise)

2. Matrix Multiplication (Replacing nested loops)

3. Broadcasting (Operating on mismatched shapes)

4. Batch Operations (Processing multi-dimensional datasets simultaneously)

#1. Replacing Element-wise Loops

In [2]:
# Non-Vectorized Loop Method

import numpy as np

features = [2,4,6,5,8,9]
weight = [1,2,2,1,3,1]

output = []

for i in range(len(features)):
  output.append(features[i] * weight[i])
  print(output)


[2]
[2, 8]
[2, 8, 12]
[2, 8, 12, 5]
[2, 8, 12, 5, 24]
[2, 8, 12, 5, 24, 9]


In [3]:
# Vectorized Method

features = np.array([2,4,6,5,8,9])
weight = np.array([1,2,2,1,3,1])

output = features * weight
print(output)

[ 2  8 12  5 24  9]


#2. Matrix Multiplication(Linear Layers)

In [5]:
#In neural networks, calculating the output for $N$ samples with $M$ features using nested loops is a major performance bottleneck.


#Suppose you have 3 samples, each with 4 features, passing through 2 neurons:

x = ([[1,2,3,4],
      [5,6,7,8],
      [9,10,11,12]])

w = ([[0.1, 0.2],
      [0.3, 0.4],
      [0.5, 0.6],
      [0.7, 0.8]]) # Added a row to match the 4 features of x

b = ([0.1, 0.2])

prediction = []

for i in range (len(x)):
  sample_output = []
  for j in range (len(w[0])):
    neuron_output = 0
    for k in range (len(x[0])):
      neuron_output += x[i][k] * w[k][j]
    neuron_output += b[j]
    sample_output.append(neuron_output)
  prediction.append(sample_output)

print(prediction)

[[5.1, 6.2], [11.499999999999998, 14.2], [17.9, 22.2]]


In [9]:
x= np.array([[1,2,3,4],
      [5,6,7,8],
      [9,10,11,12]])

w = np.array([[0.1, 0.2],
      [0.3, 0.4],
      [0.5, 0.6],
      [0.7, 0.8]])

b = np.array([0.1, 0.2])

#prediction = x @ w + b
prediction = np.dot(x,w) + b
print(prediction)


[[ 5.1  6.2]
 [11.5 14.2]
 [17.9 22.2]]


#3. Leveraging Broadcasting Rules



In [11]:
#Broadcasting eliminates the need to manually tile or duplicate vectors when performing operations between tensors of different dimensions.'

#Example: Feature Normalization (Mean Centering)
#Suppose you want to subtract the column-wise mean from a dataset of 1,000 samples and 5 features:

x = np.random.rand(500,5)
print(x)
x_mean = np.mean(x, axis = 0)
x_centred = x - x_mean
print(x_centred)

[[0.97747007 0.61847812 0.93705512 0.39004545 0.66198866]
 [0.92552268 0.62075848 0.80763984 0.39793954 0.72463744]
 [0.14027123 0.88738133 0.70915866 0.44157548 0.35005433]
 ...
 [0.36576207 0.80043069 0.28615675 0.47689854 0.26403696]
 [0.68625027 0.26539329 0.30006416 0.55587811 0.42512265]
 [0.46839516 0.66418983 0.13406643 0.15212968 0.52161134]]
[[ 0.48445204  0.11708916  0.42276905 -0.11195497  0.18867131]
 [ 0.43250465  0.11936952  0.29335378 -0.10406088  0.25132009]
 [-0.3527468   0.38599236  0.1948726  -0.06042494 -0.12326302]
 ...
 [-0.12725596  0.29904173 -0.22812931 -0.02510188 -0.20928039]
 [ 0.19323224 -0.23599567 -0.2142219   0.05387769 -0.0481947 ]
 [-0.02462287  0.16280087 -0.38021963 -0.34987074  0.04829399]]


#4. Vectorized Activation Functions & Losses

In [13]:
# Never compute activation functions (like Sigmoid, ReLU) or loss calculations sample-by-sample inside a loop.

# Vectorized Sigmoid Function sigma(Z) = 1/1 + e^-z

def vectorized_sigmoid(Z):
  return 1 / ( 1 + np.exp(-Z))
z = np.array([1,2,3,4])
print(vectorized_sigmoid(z))



[0.73105858 0.88079708 0.95257413 0.98201379]


In [1]:
import numpy as np
import time

# Create two large arrays with 1,000,000 element inputs
a = np.random.rand(1000000)
b = np.random.rand(1000000)

#  Approach 1: Non-Vectorized (Explicit Loop)
start_time = time.time()
c_loop = 0
for i in range(len(a)):
    c_loop += a[i] * b[i]
loop_time = (time.time() - start_time) * 1000  # Convert to ms

#  Approach 2: Vectorized (NumPy Dot Product)
start_time = time.time()
c_vectorized = np.dot(a, b)
vectorized_time = (time.time() - start_time) * 1000 # Convert to ms

print(f"Non-Vectorized Loop Execution Time : {loop_time:.2f} ms")
print(f"Vectorized NumPy Execution Time    : {vectorized_time:.2f} ms")
print(f"Speedup Factor                      : {loop_time / vectorized_time:.1f}x Faster!")

Non-Vectorized Loop Execution Time : 425.00 ms
Vectorized NumPy Execution Time    : 3.22 ms
Speedup Factor                      : 132.2x Faster!
